# Generated by Django 2.2.1 on 2019-06-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecera', models.CharField(max_length=2000)),
                ('cuerpo', models.CharField(max_length=2000)),
                ('url', models.CharField(max_length=2000)),
                ('esFi', models.BooleanField()),
            ],
        ),
    ]
